export const WORKPIECE_RADIUS = 0.03
export const WORKPIECE_HEIGHT = 0.08
export const WORKPIECE_DIAMETER_MM = WORKPIECE_RADIUS * 2 * 1000
export const WORKPIECE_TABLE_CENTER_Y = 0.635 + WORKPIECE_HEIGHT / 2
export const RAW_WORKPIECE_COLOR = '#556260'
export const FINISHED_WORKPIECE_COLOR = '#79a998'
